AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  sam-app

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ### Api Gateway FIXME: 不知道為啥, 直接聲明, FN 再用 RestApiId !Ref ServerlessRestApi 會發生錯誤
  # ServerlessRestApi:
  #   Type: AWS::ApiGateway::RestApi
  #   Properties:
  #     Name: ServerlessRestApi

  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sam-node-getAllItemsFunction
      CodeUri: src/handlers
      Handler: get-all-items.getAllItemsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Layers:
        - !Ref HelpersLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
            # RestApiId:
            #   Ref: ServerlessRestApi

  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sam-node-getByIdFunction
      CodeUri: src/handlers
      Handler: get-by-id.getByIdHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Layers:
        - !Ref HelpersLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
            # RestApiId:
            #   Ref: ServerlessRestApi

  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sam-node-putItemFunction
      CodeUri: src/handlers
      Handler: put-item.putItemHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Layers:
        - !Ref HelpersLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
            # RestApiId:
            #   Ref: ServerlessRestApi

  deleteByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sam-node-deleteByIdFunction
      CodeUri: src/handlers
      Handler: /delete-by-id.deleteByIdHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Layers:
        - !Ref HelpersLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: DELETE
            # RestApiId:
            #   Ref: ServerlessRestApi

  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: http-crud-tutorial-items

  HelpersLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nodelayer
      Description: layers for nodejs
      ContentUri: ./dependencies/layer
      CompatibleRuntimes:
        - nodejs18.x

Outputs:
  ApiEndpoint:
    Description: "The `invoke` URL for our HTTP API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  DdbTableName:
    Value: !Ref SampleTable
