AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  sam-app

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sam-app-getAllItemsFunction
      CodeUri: src/handlers
      Handler: get-all-items.getAllItemsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Layers:
        - !Ref HelpersLayer
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId: !Ref ExampleApiGateway

  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: get-by-id.getByIdHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
      Layers:
        - !Ref HelpersLayer
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{id}
            Method: GET
            ApiId: !Ref ExampleApiGateway

  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: put-item.putItemHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
      Layers:
        - !Ref HelpersLayer
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
            ApiId: !Ref ExampleApiGateway

  deleteByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: /delete-by-id.deleteByIdHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
      Layers:
        - !Ref HelpersLayer
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{id}
            Method: DELETE
            ApiId: !Ref ExampleApiGateway

  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: http-crud-tutorial-items

  HelpersLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nodelayer
      Description: layers for nodejs
      ContentUri: ./dependencies/layer
      CompatibleRuntimes:
        - nodejs18.x

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for dev stage"
    Value: !Sub "https://${ExampleApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev/"
